import Head from "next/head";
import Image from "next/image";
import { Poppins } from "@next/font/google";
import { HomeLayout } from "../components";
import Link from "next/link";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeLayout>
          <span>Hello</span>
          <div>
            <Link href={"/results"}>
              Go To results
            </Link>
          </div>
        </HomeLayout>
      </main>
    </>
  );
}
